name: Base

on:
    workflow_call:
      inputs:
        python:
          required: true
          type: string
        os:
          required: true
          type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    env:
      DISPLAY: ':99.0'
      QT_DEBUG_PLUGINS: 1
    steps:
      - name: Set up Python ${{ inputs.python }}
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python }}
      - name: Install package
        run: |
#         sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
          python -m pip install --upgrade pip
          pip install flake8 setuptools wheel numpy
#          pip install pytest
          pip install -e .
      - name: Linting with flake8
        run: |
          stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=docs, examples, images
#      - name: Test with pytest
#        run: |
#          pytest --cov=pymodaq --cov-report=xml -n auto
#      - name: Upload coverage to codecov.io
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          files: ./coverage.xml
#